name: Test Maven caching
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "15 */6 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  maven:
    runs-on:
      - namespace-profile-niklas-testing
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Setup Maven cache
        uses: ./ # Uses an action in the root directory
        with:
          cache: maven

      - uses: actions/checkout@v3
        with:
          repository: namespace-integration-demos/selenium-cache
          path: demo

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - run: chrome --version

      - name: Build with Maven
        run: mvn -B clean test
        working-directory: ./demo

      - name: Print cache metadata file
        run: |
          ls -al /cache/.ns
          cat /cache/.ns/cache-metadata.json
