name: Test PNPM caching
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pnpm:
    runs-on:
      - namespace-profile-e2e-small
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Setup PNPM cache
        uses: ./ # Uses an action in the root directory
        with:
          cache: pnpm
      - uses: actions/checkout@v3
        with:
          repository: PostHog/posthog
          path: demo
      - run: pnpm install --frozen-lockfile
        working-directory: ./demo
