name: Test Python caching
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  python:
    runs-on:
      - namespace-profile-niklas-testing
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python Pip cache
        uses: ./ # Uses an action in the root directory
        with:
          cache: python
      - uses: actions/checkout@v3
        with:
          repository: namespace-integration-demos/python-cache
          path: demo
      - run: pip install -r ./requirements.txt
        working-directory: ./demo
      - name: Print cache metadata file
        run :
          cat /cache/.ns/cache-metadata.json