name: Test Python caching
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "25 */6 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  python:
    runs-on:
      - namespace-profile-e2e-small
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python Pip cache
        uses: ./ # Uses an action in the root directory
        with:
          cache: python

      - uses: actions/checkout@v3
        with:
          repository: namespace-integration-demos/python-cache
          path: demo

      - run: pip install -r ./requirements.txt
        working-directory: ./demo

      - name: Print cache metadata file
        run: |
          ls -al /cache/.ns
          cat /cache/.ns/cache-metadata.json
