name: Test Rust caching
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rust:
    runs-on:
      - namespace-profile-e2e-small
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust cache
        uses: ./ # Uses an action in the root directory
        with:
          cache: rust
      - uses: actions/checkout@v3
        with:
          repository: namespace-integration-demos/rust-cache
          path: demo
      - run: cargo build --locked --release --no-default-features --all
        working-directory: ./demo
      - run: cargo test --locked --release --all
        working-directory: ./demo
      - name: Print cache metadata file
        run :
          cat /cache/.ns/cache-metadata.json