name: Test Yarn caching
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "35 */6 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  yarn:
    runs-on:
      - namespace-profile-niklas-testing
    steps:
      - uses: actions/checkout@v4

      - name: Setup Yarn cache
        uses: ./ # Uses an action in the root directory
        with:
          cache: yarn

      - uses: actions/checkout@v4
        with:
          repository: namespace-integration-demos/cache-yarn-workspaces
          path: demo

      - run: yarn
        working-directory: ./demo

      - run: yarn workspace @project/web-app build
        working-directory: ./demo

      - name: Print cache metadata file
        run: |
          ls -al /cache/.ns
          cat /cache/.ns/cache-metadata.json
