name: Test Yarn caching
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  yarn:
    runs-on:
      - namespace-profile-e2e-small
    steps:
      - uses: actions/checkout@v3
      - name: Setup Yarn cache
        uses: ./ # Uses an action in the root directory
        with:
          cache: yarn
      - uses: actions/checkout@v3
        with:
          repository: namespace-integration-demos/cache-yarn-workspaces
          path: demo
      - run: yarn
        working-directory: ./demo
      - run: yarn workspace @project/web-app build
        working-directory: ./demo
